---
- hosts: all  #group name from the inventory
  sudo: true


  tasks:
      - name: Add a list of users
        user: name={{ item }} state=present
        with_items:
          - user4
          - user5
          - user6
...

